# ===========================================================
# Model configuration. it is formatted as follows:

#models: 
# <model_name>:
#   environment: <name of this models environment>
#   model_path: <path to the folder that contains the model cache or model file> 
#   material: <name of material model will analyse. This should be registered in material_config.yml>  

# For neatness, my model_path paths all look like (wrt the repo): "assets\models\<model_name>\" 
# and i then let the get_calc.py handle the specifics of the actual downloaded model package
# <model_name> should be the same name as what is checked in get_calc.py. 

# ============================================================


models:

  small-omat-0: # part of the mace family.
    environment: mace_env
    model_path: assets/models/small-omat-0
    material: hbn

  orb:
    environment: orb_env
    model_path: assets/models/orb
    material: hbn

  pet-mad:
    environment: petmad_env 
    model_path: assets/models/petmad
    material: hbn

  chgnet:
    environment: chgnet_env
    model_path: assets/models/chgnet
    material: hbn

  mattersim:
    environment: mattersim_env
    model_path: assets/models/mattersim
    material: hbn


# ============================================================
# Structure configuration 
#
# This file is formatted as follows:
#
# structures:
#   <structure_name>:
#     file_path: <relative path to POSCAR>
#     is_file_relaxed: <true|false>
#     crystal_type: <one of the keys in kpoint_registry>
#
#     phonons:
#       supercell_matrix: [Nx, Ny, Nz]
#       delta: <finite displacement amplitude in Angstrom>
#       
#       want_band_structure: <true|false> # False means the next two entries are not required 
#       band_structure:
#         band_path: <one of the keys in kpoint_dictionary.<crystal_type>.paths>
#         primtive_cell_path: <relative path to primtive cell POSCAR>
#
#       dos:
#         kpts: [kx, ky, kz] # how many sampling locations in the brillouin zone to collect phonon frequencies.
#         npts: <int> # how many bins used to represent the DOS.
#         width_ev: <float> # gaussian broadening in eV applied to DOS. It smoothes the spectrum. 
# ============================================================


# for defects, supply the supercell, for crystals, 
structures:
  diamond:
    file_path: assets/structures/diamond_super.poscar
    is_file_relaxed: false
    is_file_primitive_cell: True
    supercell_matrix: (3,3,3) 

    crystal_type: fcc

    phonons:
      delta: 0.01 # displacement size

      want_band_structure: true 
      band_structure:
        band_path: bulk
        primitive_cell_path: assets/structures/diamond_primitive.poscar

      dos:
        kpts: [12, 12, 12]
        npts: 400
        width_ev: 1e-3


  diamond_nv:
    file_path: assets/structures/diamond_nv.poscar
    is_file_relaxed: false
    crystal_type: fcc

    phonons:
      supercell_matrix: [1, 1, 1]
      delta: 0.01

      want_band_structure: False
      band_structure:
        band_path: None # these entries do not matter. can be skipped
        primtive_cell_path: None # can be skipped

      dos:
        kpts: [12, 12, 12]
        npts: 400
        width_ev: 1e-3


  hbn:
    file_path: assets/structures/hbn_super.poscar
    is_file_relaxed: false
    crystal_type: hex

    phonons:
      supercell_matrix: [2, 2, 1]
      delta: 0.01

      want_band_structure: true
      band_structure:
        band_path: bulk
        primitive_cell_path: assets/structures/hbn_primitive.poscar

      dos:
        kpts: [12, 12, 12]
        npts: 400
        width_ev: 1e-3


  hbn_c2:
    file_path: assets/structures/hbn_c2.poscar
    is_file_relaxed: false
    crystal_type: hex

    phonons:
      supercell_matrix: [1, 1, 1]
      delta: 0.01

      want_band_structure: false
      
      dos:
        kpts: [12, 12, 12]
        npts: 400
        width_ev: 1e-3


# =============================================================
# k-points dictionary (Setyawan and Curtarolo 2010)
#
# For each crystal_type: #TODO: include all crystal types. 
#   - special_points: dict of label -> fractional coordinates (b1,b2,b3 basis)
#   - paths: named standard paths. Each path has a "path" string usable by ASE.
# NOTE: as of now i dont think separations are accepted in the path string. 
# ============================================================

kpoint_dictionary:

  # Face-centered cubic (FCC) (diamond)
  fcc:
    special_points:
      G: [0.0, 0.0, 0.0]
      X: [0.5, 0.0, 0.5]
      W: [0.5, 0.25, 0.75]
      K: [0.375, 0.375, 0.75]
      L: [0.5, 0.5, 0.5]
      U: [0.625, 0.25, 0.625]

    paths:
      bulk:
        # Γ-X-W-K-Γ-L-U-W-L-K | U-X
        path: GXWKGLUWLKUX #TODO: need to test whether i can implement the break (denoted by | in the above, but 
        # i believe is denoted by ',' in ase, without breakages)


  # Hexagonal (HEX) (bulk hBN)
  hex:
    special_points:
      G: [0.0, 0.0, 0.0]
      M: [0.5, 0.0, 0.0]
      K: [0.333333333333, 0.333333333333, 0.0]
      A: [0.0, 0.0, 0.5]
      L: [0.5, 0.0, 0.5]
      H: [0.333333333333, 0.333333333333, 0.5]

    paths:
      bulk:
        # Γ-M-K-Γ-A-L-H-A | L-M | K-H
        path: GMKGALHA #LMKH #GMKGALHA,LM,KH
      monolayer:
        # Γ-M-K-Γ (first part)
        path: GMKG


  # Cubic primitive (CUB) 
  cub:
    special_points:
      G: [0.0, 0.0, 0.0]
      X: [0.0, 0.5, 0.0]
      M: [0.5, 0.5, 0.0]
      R: [0.5, 0.5, 0.5]

    paths:
      bulk:
        # Γ-X-M-Γ-R-X | M-R
        path: GXMGRXMR #GXMGRX,MR


  # Body-centered cubic (BCC, cI)
  bcc:
    special_points:
      G: [0.0, 0.0, 0.0]
      H: [0.5, -0.5, 0.5]
      N: [0.0, 0.0, 0.5]
      P: [0.25, 0.25, 0.25]

    paths:
      bulk:
        # Γ-H-N-Γ-P-H | P-N
        path: GHNGPHPN #GHNGPH,PN
