defaults:
  model_name:
    - pet-mad-s-v1.1.0
    - petmad_demo_neb_ft
  outputs_root: results
  models_root: ../../../../assets/models
  device: cuda
  dtype: float32
  overwrite: true
  include_vdw: true
  relax_endpoints: false
  remap_f_i: true
  poscar_i: ../../../0_raw_inputs/output1/00/POSCAR
  poscar_f: ../../../0_raw_inputs/output1/07/POSCAR
  dft_neb_dat: ../../../0_raw_inputs/output1/neb.dat
workflows:
  neb:
    settings:
      n_images_fallback: 8
      fmax_mlip_guess: 0.03
      steps_mlip_guess: 300
      fmax_mlip_d3: 0.03
      steps_mlip_d3: 1400
      fmax_ci: 0.03
      steps_ci: 200
